version: "3.7"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
  web:
    build: .
    env_file:
      - ./.env.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    depends_on:
      - db